###
POST http://localhost:3000/api/post HTTP/1.1
Content-Type:  application/json

{
    "name":"kjsdfk",
    "age":30,
    "email":"testemail"
}

###
POST http://localhost:3000/api/post HTTP/1.1
Content-Type: application/json

{
    "name":"kjsdfk",
    "age":30,
    "email":"testemail"
}
